spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 200709
    url: jdbc:postgresql://103.71.50.209:5432/mall
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
